#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Git Bash mangles arguments that look like POSIX paths when handing them to
# native Windows executables (curl.exe). Turn that off for the whole run.
export MSYS_NO_PATHCONV=1
export MSYS2_ARG_CONV_EXCL='*'

# Hermes reads its config from ~/.hermes/.env — so that IS our env file. The
# library's write_env preserves every other line, and re-runs offer the
# current value back as the default.
mkdir -p "$HOME/.hermes"
ENV_FILE="$HOME/.hermes/.env"

# Everything captured lands here. WORKDIR is the Harness's cwd, kept separate
# so stray files (Hermes writes trajectory_samples.jsonl into cwd) are
# obvious rather than mixed into your real work.
CAPTURE_DIR="$HOME/hermes-capture-$(date +%Y%m%d-%H%M%S)"
WORKDIR="$CAPTURE_DIR/workdir"
mkdir -p "$WORKDIR"
MANIFEST="$CAPTURE_DIR/manifest.txt"

PY=""
SERVE_PID=""

# note_manifest "..." — append a line to the run manifest.
note_manifest() { printf '%s\n' "$1" >> "$MANIFEST"; }

# capture_get NAME URL [auth] — GET a URL, save the raw body, report status.
capture_get() {
  local name="$1" url="$2" auth="${3:-}" code
  local out="$CAPTURE_DIR/$name"
  if [[ -n "$auth" ]]; then
    code=$(curl -sS -o "$out" -w '%{http_code}' -H "Authorization: Bearer $auth" "$url" 2>>"$CAPTURE_DIR/curl-errors.log" || echo "000")
  else
    code=$(curl -sS -o "$out" -w '%{http_code}' "$url" 2>>"$CAPTURE_DIR/curl-errors.log" || echo "000")
  fi
  if [[ "$code" == "200" ]]; then
    printf '  %s✓%s %s → %s (%s bytes)\n' "$GREEN" "$RESET" "$url" "$name" "$(wc -c < "$out" | tr -d ' ')"
  else
    warn "$url returned HTTP $code — saved anyway as $name"
  fi
  note_manifest "GET $url -> HTTP $code -> $name"
}

banner "Hermes → LM Studio: capture raw output"

# ── Stage 1 ────────────────────────────────────────────────────────────────
stage "Preflight — tools and versions"
say "Checking everything this needs before we touch any config."
printf '\n'

for c in python python3 py; do
  if command -v "$c" >/dev/null 2>&1; then PY="$c"; break; fi
done
if [[ -z "$PY" ]]; then
  warn "No python on PATH. Hermes is a Python program, so this is surprising."
  say "This wizard needs it to read JSON (jq isn't assumed on Windows)."
  exit 1
fi
say "python:  $PY ($($PY --version 2>&1))"

command -v curl >/dev/null 2>&1 || { warn "curl not found — unexpected in Git Bash."; exit 1; }
say "curl:    $(curl --version 2>&1 | head -n1)"

if ! command -v hermes >/dev/null 2>&1; then
  warn "hermes is not on PATH in this shell."
  say "If you installed it with pipx/uv, open the shell where 'hermes --version' works."
  exit 1
fi
say "hermes:  $(hermes --version 2>&1 | head -n1)"

printf '\n'
say "Checking that the API server extra is installed..."
if hermes serve --help >/dev/null 2>&1; then
  say "  'hermes serve' is available."
else
  warn "'hermes serve' failed. It needs the [web] extra."
  say "Install it, then re-run:  pip install -e '.[web]'   (or your installer's equivalent)"
  exit 1
fi
note "The [pty] extra is POSIX-only. On Windows its embedded chat socket may not"
note "work — that's fine, we only use the HTTP+SSE API, which does not need it."

note_manifest "=== Hermes capture run: $(date -Iseconds) ==="
note_manifest "OS: Windows (Git Bash) — $(uname -a 2>/dev/null || echo unknown)"
note_manifest "python: $($PY --version 2>&1)"
note_manifest "hermes: $(hermes --version 2>&1 | head -n1)"
note_manifest "capture dir: $CAPTURE_DIR"
note_manifest ""

printf '\n'
say "Capturing into: $CAPTURE_DIR"
pause "Looks right?"

# ── Stage 2 ────────────────────────────────────────────────────────────────
stage "LM Studio — confirm it's serving, capture its model list"
say "LM Studio must have its local server running (Developer tab → Start Server)."
say "Default port is 1234."
printf '\n'
note "Using 127.0.0.1 rather than localhost: on Windows, localhost can resolve to"
note "::1 first and miss a server bound only to IPv4."
ask LMSTUDIO_URL "LM Studio base URL [http://127.0.0.1:1234]:"
[[ -z "$LMSTUDIO_URL" ]] && LMSTUDIO_URL="http://127.0.0.1:1234"
printf '\n'

capture_get "lmstudio-models.json" "$LMSTUDIO_URL/api/v1/models"
if [[ ! -s "$CAPTURE_DIR/lmstudio-models.json" ]]; then
  warn "Nothing came back. Is the LM Studio server started?"
  say "Older LM Studio (<0.4.0) uses /api/v0/models — trying that too."
  capture_get "lmstudio-models-v0.json" "$LMSTUDIO_URL/api/v0/models"
fi

printf '\n'
say "Model ids found:"
$PY - "$CAPTURE_DIR/lmstudio-models.json" <<'PYEOF' 2>/dev/null || say "  (couldn't parse — open the file and read the ids yourself)"
import json, sys
d = json.load(open(sys.argv[1], encoding="utf-8"))
items = d.get("models") or d.get("data") or []
for m in items:
    print("   ", m.get("id") or m.get("modelKey") or m.get("path"))
PYEOF

printf '\n'
step "Pick one that is loaded (or that LM Studio will JIT-load) and paste its id."
ask HERMES_INFERENCE_MODEL "Model id:"
note_manifest "LM Studio URL: $LMSTUDIO_URL"
note_manifest "Model: $HERMES_INFERENCE_MODEL"

# ── Stage 3 ────────────────────────────────────────────────────────────────
stage "Wire Hermes to LM Studio"
say "Writing to $ENV_FILE. Other lines in that file are preserved."
printf '\n'

write_env OPENAI_BASE_URL "$LMSTUDIO_URL/v1"
write_env OPENAI_API_KEY "lm-studio"
write_env HERMES_INFERENCE_MODEL "$HERMES_INFERENCE_MODEL"

printf '\n'
say "Now the API server. It needs a bearer token — any non-empty string."
ask_secret API_SERVER_KEY "API server key [Enter to generate one]:"
if [[ -z "$API_SERVER_KEY" ]]; then
  API_SERVER_KEY="capture-$(date +%s)-$RANDOM"
  say "Generated: $API_SERVER_KEY"
fi
write_env API_SERVER_ENABLED "true"
write_env API_SERVER_KEY "$API_SERVER_KEY"

printf '\n'
ask HERMES_PORT "Port for hermes serve [8080]:"
[[ -z "$HERMES_PORT" ]] && HERMES_PORT="8080"
HERMES_BASE="http://127.0.0.1:$HERMES_PORT"
note_manifest "hermes serve: $HERMES_BASE"

printf '\n'
warn "If the docs on this version use 'base_url' rather than 'api'/OPENAI_BASE_URL,"
warn "the next stage will fail loudly — that mismatch is itself a finding worth"
warn "recording (it's item 7 on the research doc's empirical list)."
pause "Continue?"

# ── Stage 4 ────────────────────────────────────────────────────────────────
stage "Baseline — one-shot plain text, before any server"
say "'hermes -z' prints the final response and nothing else. If this works, the"
say "model wiring is correct, and we learn the exit code (undocumented — item 4)."
printf '\n'

cd "$WORKDIR"
set +e
hermes -z "Reply with exactly the word: hello. Do not use any tools." \
  --usage-file "$CAPTURE_DIR/baseline-usage.json" \
  > "$CAPTURE_DIR/baseline-stdout.txt" 2> "$CAPTURE_DIR/baseline-stderr.txt"
BASELINE_EXIT=$?
set -e

say "exit code: $BASELINE_EXIT   ← record this, it is undocumented"
note_manifest "hermes -z exit code: $BASELINE_EXIT"
printf '\n'
say "stdout was:"
sed 's/^/    /' "$CAPTURE_DIR/baseline-stdout.txt" | head -n 10
printf '\n'
if [[ "$BASELINE_EXIT" -ne 0 ]]; then
  warn "Non-zero exit. Check baseline-stderr.txt before going on."
  say "  $CAPTURE_DIR/baseline-stderr.txt"
  confirm "Continue anyway?" || exit 1
fi
pause "Ready to start the server?"

# ── Stage 5 ────────────────────────────────────────────────────────────────
stage "Start hermes serve, capture the static surfaces"
say "Starting in the background, cwd = $WORKDIR"
printf '\n'

cd "$WORKDIR"
hermes serve --host 127.0.0.1 --port "$HERMES_PORT" \
  > "$CAPTURE_DIR/serve-stdout.log" 2> "$CAPTURE_DIR/serve-stderr.log" &
SERVE_PID=$!
say "pid $SERVE_PID — logs in serve-stdout.log / serve-stderr.log"

printf '\n'
say "Waiting for /health..."
READY=""
for i in $(seq 1 45); do
  if curl -sS -o /dev/null --max-time 2 "$HERMES_BASE/health" 2>/dev/null; then READY="yes"; break; fi
  sleep 2
done
if [[ -z "$READY" ]]; then
  warn "Server didn't come up in 90s. Read serve-stderr.log — first run may be building."
  confirm "Keep waiting / continue anyway?" || { kill "$SERVE_PID" 2>/dev/null || true; exit 1; }
fi

printf '\n'
capture_get "hermes-capabilities.json" "$HERMES_BASE/v1/capabilities" "$API_SERVER_KEY"
capture_get "hermes-models.json"       "$HERMES_BASE/v1/models"       "$API_SERVER_KEY"
capture_get "hermes-health.json"       "$HERMES_BASE/health/detailed" "$API_SERVER_KEY"

printf '\n'
say "/v1/capabilities is the machine-readable description of the stable surface."
say "It is the best available evidence for what POST /v1/runs expects — the"
say "request body shape is NOT documented anywhere, so read it now:"
printf '\n'
$PY -m json.tool "$CAPTURE_DIR/hermes-capabilities.json" 2>/dev/null | head -n 40 || head -c 2000 "$CAPTURE_DIR/hermes-capabilities.json"
printf '\n'
pause "Read it — full copy is in hermes-capabilities.json. Press Enter."

# ── Stage 6 ────────────────────────────────────────────────────────────────
stage "Capture the PLAIN exchange (no tools)"
say "This is the primary artefact. Raw SSE bytes, unparsed."
printf '\n'

cat > "$CAPTURE_DIR/run-plain.json" <<'JSONEOF'
{
  "prompt": "Reply with exactly the word: hello. Do not use any tools."
}
JSONEOF

say "Request body written to run-plain.json:"
sed 's/^/    /' "$CAPTURE_DIR/run-plain.json"
printf '\n'
warn "This body is a best guess — the schema is undocumented."
step "If /v1/capabilities showed a different shape, edit that file now, then continue."
pause "Edited (or happy as-is)?"

printf '\n'
RUN_RESP="$CAPTURE_DIR/run-plain-response.json"
RUN_CODE=$(curl -sS -o "$RUN_RESP" -w '%{http_code}' \
  -H "Authorization: Bearer $API_SERVER_KEY" \
  -H "Content-Type: application/json" \
  --data @"$CAPTURE_DIR/run-plain.json" \
  "$HERMES_BASE/v1/runs" 2>>"$CAPTURE_DIR/curl-errors.log" || echo "000")
say "POST /v1/runs → HTTP $RUN_CODE"
note_manifest "POST /v1/runs (plain) -> HTTP $RUN_CODE"

if [[ "$RUN_CODE" != "200" && "$RUN_CODE" != "201" && "$RUN_CODE" != "202" ]]; then
  warn "Rejected. The response body tells you the real schema:"
  sed 's/^/    /' "$RUN_RESP" | head -n 20
  say "Fix run-plain.json to match and re-run this wizard."
  confirm "Continue to shutdown?" || true
else
  RUN_ID=$($PY -c 'import json,sys; d=json.load(open(sys.argv[1],encoding="utf-8")); print(d.get("id") or d.get("run_id") or d.get("runId") or "")' "$RUN_RESP" 2>/dev/null || echo "")
  if [[ -z "$RUN_ID" ]]; then
    say "Response was:"; sed 's/^/    /' "$RUN_RESP" | head -n 20
    ask RUN_ID "Couldn't find the run id — paste it:"
  fi
  say "run id: $RUN_ID"
  note_manifest "plain run id: $RUN_ID"

  printf '\n'
  warn "Note for the design: we POST first, then attach to /events. If the early"
  warn "events are missing from the capture, that means the stream does NOT replay"
  warn "from the start — which is a real finding for the replay-semantics ticket."
  printf '\n'
  say "Attaching to the SSE stream (up to 300s)..."
  curl -sS -N --max-time 300 \
    -H "Authorization: Bearer $API_SERVER_KEY" \
    "$HERMES_BASE/v1/runs/$RUN_ID/events" \
    > "$CAPTURE_DIR/plain-events.sse" 2>>"$CAPTURE_DIR/curl-errors.log" || true

  say "captured $(wc -l < "$CAPTURE_DIR/plain-events.sse" | tr -d ' ') lines → plain-events.sse"
  capture_get "plain-run-final.json" "$HERMES_BASE/v1/runs/$RUN_ID" "$API_SERVER_KEY"
  printf '\n'
  say "First 20 lines:"
  head -n 20 "$CAPTURE_DIR/plain-events.sse" | sed 's/^/    /'
fi
printf '\n'
pause "Press Enter for the tool-call capture."

# ── Stage 7 ────────────────────────────────────────────────────────────────
stage "Capture the TOOL-CALL exchange"
say "Same again, but with a prompt that forces a tool. This gives you the"
say "tool.start / tool.progress / tool.complete payloads — item 1 on the"
say "empirical list, and the thing the whole Event model is blocked on."
printf '\n'

printf 'alpha\nbeta\ngamma\n' > "$WORKDIR/sample.txt"
say "Created $WORKDIR/sample.txt for it to read."

cat > "$CAPTURE_DIR/run-tool.json" <<'JSONEOF'
{
  "prompt": "Use your terminal tool to list the files in the current directory, then tell me how many there are."
}
JSONEOF
printf '\n'
say "Body: run-tool.json (same shape as the plain one — edit if you changed that)."
pause "Ready?"

printf '\n'
TOOL_RESP="$CAPTURE_DIR/run-tool-response.json"
TOOL_CODE=$(curl -sS -o "$TOOL_RESP" -w '%{http_code}' \
  -H "Authorization: Bearer $API_SERVER_KEY" \
  -H "Content-Type: application/json" \
  --data @"$CAPTURE_DIR/run-tool.json" \
  "$HERMES_BASE/v1/runs" 2>>"$CAPTURE_DIR/curl-errors.log" || echo "000")
say "POST /v1/runs → HTTP $TOOL_CODE"
note_manifest "POST /v1/runs (tool) -> HTTP $TOOL_CODE"

if [[ "$TOOL_CODE" == "200" || "$TOOL_CODE" == "201" || "$TOOL_CODE" == "202" ]]; then
  TOOL_RUN_ID=$($PY -c 'import json,sys; d=json.load(open(sys.argv[1],encoding="utf-8")); print(d.get("id") or d.get("run_id") or d.get("runId") or "")' "$TOOL_RESP" 2>/dev/null || echo "")
  [[ -z "$TOOL_RUN_ID" ]] && ask TOOL_RUN_ID "Paste the run id:"
  note_manifest "tool run id: $TOOL_RUN_ID"

  printf '\n'
  warn "Hermes only gates DANGEROUS commands by default (approvals.mode: smart),"
  warn "so 'ls' will very likely NOT produce an approval.request. Absence of one"
  warn "here is expected, not a failure."
  printf '\n'
  say "Attaching to the SSE stream (up to 300s)..."
  curl -sS -N --max-time 300 \
    -H "Authorization: Bearer $API_SERVER_KEY" \
    "$HERMES_BASE/v1/runs/$TOOL_RUN_ID/events" \
    > "$CAPTURE_DIR/tool-events.sse" 2>>"$CAPTURE_DIR/curl-errors.log" || true

  say "captured $(wc -l < "$CAPTURE_DIR/tool-events.sse" | tr -d ' ') lines → tool-events.sse"
  capture_get "tool-run-final.json" "$HERMES_BASE/v1/runs/$TOOL_RUN_ID" "$API_SERVER_KEY"
  printf '\n'
  say "Event types seen:"
  grep -oE '"(type|event)"[[:space:]]*:[[:space:]]*"[^"]+"' "$CAPTURE_DIR/tool-events.sse" 2>/dev/null | sort -u | sed 's/^/    /' | head -n 30 || say "    (none matched — inspect the file by hand)"
else
  warn "Rejected — see run-tool-response.json"
fi
printf '\n'
pause "Press Enter to wrap up."

# ── Stage 8 ────────────────────────────────────────────────────────────────
stage "Stray files, shutdown, and bundle"

say "Checking whether Hermes littered its working directory..."
printf '\n'
FOUND_STRAY=""
for f in trajectory_samples.jsonl failed_trajectories.jsonl; do
  if [[ -f "$WORKDIR/$f" ]]; then
    say "  found $f ($(wc -c < "$WORKDIR/$f" | tr -d ' ') bytes) — copying"
    cp "$WORKDIR/$f" "$CAPTURE_DIR/"
    FOUND_STRAY="yes"
    note_manifest "stray file confirmed: $f"
  fi
done
if [[ -z "$FOUND_STRAY" ]]; then
  say "  none — trajectory files did not appear in cwd."
  note_manifest "stray trajectory files: none observed"
fi

printf '\n'
say "Stopping the server..."
hermes serve --stop >/dev/null 2>&1 || true
if [[ -n "$SERVE_PID" ]] && kill -0 "$SERVE_PID" 2>/dev/null; then
  kill "$SERVE_PID" 2>/dev/null || true
  sleep 2
  kill -0 "$SERVE_PID" 2>/dev/null && warn "Still running as pid $SERVE_PID — use Task Manager or: taskkill //PID $SERVE_PID //F"
fi
say "  stopped."

note_manifest ""
note_manifest "Finished: $(date -Iseconds)"

printf '\n'
say "Everything is in:"
say "  $CAPTURE_DIR"
printf '\n'
ls -1 "$CAPTURE_DIR" | sed 's/^/    /'

printf '\n'
say "The two files that matter most:"
say "  plain-events.sse         ← the plain exchange"
say "  tool-events.sse          ← the tool-call payloads"
say "  hermes-capabilities.json ← the stable-surface description"
printf '\n'
step "Copy the whole folder back to the CapStone repo as docs/research/captures/"
step "Then resolve ticket 03 with the manifest contents."
printf '\n'
warn "Redact API_SERVER_KEY from manifest.txt if you commit this anywhere."

finish
