#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Git Bash mangles POSIX-looking arguments when handing them to native Windows
# executables. ssh.exe and scp.exe are native, so turn that off for the run.
export MSYS_NO_PATHCONV=1
export MSYS2_ARG_CONV_EXCL='*'

# The wizard's own bookkeeping — it exists so re-runs offer previous answers
# back as defaults. Nothing else reads it.
ENV_FILE="$HOME/.remote-host.env"

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
LANDING="$REPO_ROOT/docs/research/captures/remote-host"
mkdir -p "$LANDING"
MANIFEST="$LANDING/manifest.txt"

note_manifest() { printf '%s\n' "$1" >> "$MANIFEST"; }

# SSH_SETUP_SECONDS accumulates stages 3 and 4 — the honest input to the
# "manual Daemon install" decision in ticket 12. Measured, not estimated.
SSH_SETUP_SECONDS=0

_TOP_PID=$$

# _unreachable — abort the whole run. Reached only when SSH itself fails, never
# when a remote command merely returns non-zero.
_unreachable() {
  printf '\n'
  warn "Lost the SSH connection to $HOST_USER@$HOST_ADDR:${SSH_PORT:-22}."
  note "    ssh -vvv ${SSH_KEY_PATH:+-i $SSH_KEY_PATH} -p ${SSH_PORT:-22} $HOST_USER@$HOST_ADDR"
  note "Common causes: the Host slept, DHCP moved its address, or Wi-Fi dropped."
  printf '\n'
  say "Stopping here on purpose. Re-run when the Host answers — the wizard"
  say "remembers your answers and picks up from the start."
  note_manifest "ABORTED: SSH unreachable at $(date -Iseconds)"
  exit 1
}
trap _unreachable TERM

# rsh "command" — run a command on the Host, non-interactively.
#
# Aborts the run if SSH cannot connect, rather than letting the failure look
# like a result. Without this, a Host that sleeps mid-run writes "NOT INSTALLED"
# into harness-versions.txt and "no Vendor serving" into the manifest — a
# dropped connection entering the record as a research finding.
#
# ssh reserves 255 for its own errors; a remote command's own exit code passes
# through untouched, because those codes ARE findings (Hermes exiting 1 on a
# tool call is in the existing captures). A remote command that genuinely
# returns 255 is indistinguishable, and rare enough to accept.
#
# The kill is not decoration: half these calls sit inside $(...), and an exit
# there would only leave the subshell and be swallowed by the '|| echo 000'
# that follows. Signalling the top-level PID stops the run for real.
rsh() {
  local rc=0
  ssh -o BatchMode=yes -o ConnectTimeout=10 \
      ${SSH_KEY_PATH:+-i "$SSH_KEY_PATH"} -p "${SSH_PORT:-22}" \
      "$HOST_USER@$HOST_ADDR" "$1" || rc=$?
  if (( rc == 255 )); then
    kill -s TERM "$_TOP_PID" 2>/dev/null
    exit 255
  fi
  return $rc
}

banner "Stand up a remote Host — issue #4"

# ── Stage 1 ────────────────────────────────────────────────────────────────
stage "Preflight — this machine"
say "This wizard runs where you sit. It drives the Host over SSH."
printf '\n'
for c in ssh scp ssh-keygen curl; do
  if command -v "$c" >/dev/null 2>&1; then
    say "$c: $(command -v "$c")"
  else
    warn "$c not found — install OpenSSH before continuing."; exit 1
  fi
done
printf '\n'
note_manifest "=== Remote Host capture run: $(date -Iseconds) ==="
note_manifest "Client: $(uname -a 2>/dev/null || echo unknown)"
say "Transcripts will land in: $LANDING"
pause "Ready?"

# ── Stage 2 ────────────────────────────────────────────────────────────────
stage "Host facts"
say "The Host is a SEPARATE machine. That separateness is the whole point of"
say "this ticket — every finding so far came from one box."
printf '\n'
ask HOST_OS      "Host OS — 'windows' or 'macos':"
ask HOST_ADDR    "Host address (LAN IP or hostname):"
ask HOST_USER    "Username on the Host:"
ask SSH_PORT     "SSH port [22]:"
[[ -z "$SSH_PORT" ]] && SSH_PORT=22
write_env HOST_OS   "$HOST_OS"
write_env HOST_ADDR "$HOST_ADDR"
write_env HOST_USER "$HOST_USER"
write_env SSH_PORT  "$SSH_PORT"
note_manifest "Host: $HOST_USER@$HOST_ADDR:$SSH_PORT ($HOST_OS)"
pause "Continue?"

# ── Stage 3 ────────────────────────────────────────────────────────────────
stage "Enable the SSH server on the Host"
_T0=$SECONDS
say "Do this AT the Host, on its own keyboard. Count your steps as you go."
printf '\n'
if [[ "$HOST_OS" == "windows" ]]; then
  step "Settings -> System -> Optional features -> Add an optional feature"
  step "Search 'OpenSSH Server', install it"
  step "Open PowerShell as Administrator, then run:"
  note "    Start-Service sshd"
  note "    Set-Service -Name sshd -StartupType Automatic"
  warn "Windows puts an admin user's keys in ProgramData\\ssh\\administrators_authorized_keys,"
  warn "NOT in the home directory. Stage 4 handles that; do not fight it here."
else
  step "System Settings -> General -> Sharing -> turn on 'Remote Login'"
  step "Note the address it shows under the toggle"
  note "    Or from a terminal: sudo systemsetup -setremotelogin on"
fi
printf '\n'
pause "Done — SSH server is running on the Host?"
_T3=$((SECONDS - _T0))
SSH_SETUP_SECONDS=$((SSH_SETUP_SECONDS + _T3))
note_manifest "Stage 3 (enable sshd) wall clock: ${_T3}s"

# ── Stage 4 ────────────────────────────────────────────────────────────────
stage "Key auth — generate, copy, verify"
_T0=$SECONDS
SSH_KEY_PATH="$HOME/.ssh/id_ed25519_capstone_host"
if [[ -f "$SSH_KEY_PATH" ]]; then
  say "Key already exists: $SSH_KEY_PATH"
else
  say "Generating an ed25519 key dedicated to this Host."
  ssh-keygen -t ed25519 -f "$SSH_KEY_PATH" -C "capstone-host" -N ""
fi
write_env SSH_KEY_PATH "$SSH_KEY_PATH"
printf '\n'
say "Public key:"
note "$(cat "$SSH_KEY_PATH.pub")"
printf '\n'
if [[ "$HOST_OS" == "windows" ]]; then
  say "ssh-copy-id does not exist on Windows. Paste the key by hand:"
  step "On the Host, open PowerShell as Administrator"
  step "For an ADMIN account, append the line above to the file:"
  note "    C:\\ProgramData\\ssh\\administrators_authorized_keys"
  step "For a standard account, append it to .ssh\\authorized_keys in the home dir"
  step "Then fix the ACL — sshd refuses a world-readable key file:"
  note "    icacls C:\\ProgramData\\ssh\\administrators_authorized_keys /inheritance:r"
  note "    icacls C:\\ProgramData\\ssh\\administrators_authorized_keys /grant SYSTEM:F"
else
  say "Copying the key to the Host — this asks for the password ONE last time."
  if command -v ssh-copy-id >/dev/null 2>&1; then
    ssh-copy-id -i "$SSH_KEY_PATH.pub" -p "$SSH_PORT" "$HOST_USER@$HOST_ADDR" || \
      warn "ssh-copy-id failed — paste the key into authorized_keys by hand."
  else
    warn "ssh-copy-id missing — paste the key into authorized_keys by hand."
  fi
fi
printf '\n'
pause "Key is in place on the Host?"
printf '\n'
say "Verifying key-only auth (BatchMode refuses to fall back to a password)..."
# Raw ssh, not rsh: a rejected key exits 255 exactly like an unreachable Host,
# and here the cause is almost certainly the key, so say that instead.
if ssh -o BatchMode=yes -o ConnectTimeout=10 -i "$SSH_KEY_PATH" \
     -p "$SSH_PORT" "$HOST_USER@$HOST_ADDR" "echo ok" 2>/dev/null | grep -q ok; then
  printf '  %s+%s key auth works — no password prompt\n' "$GREEN" "$RESET"
  note_manifest "SSH key auth: VERIFIED (BatchMode, no password fallback)"
else
  warn "Key auth failed. Diagnose before continuing:"
  note "    ssh -vvv -i $SSH_KEY_PATH -p $SSH_PORT $HOST_USER@$HOST_ADDR"
  note_manifest "SSH key auth: FAILED"
  exit 1
fi
_T4=$((SECONDS - _T0))
SSH_SETUP_SECONDS=$((SSH_SETUP_SECONDS + _T4))
note_manifest "Stage 4 (key auth) wall clock: ${_T4}s"
printf '\n'
say "Total SSH setup so far: ${SSH_SETUP_SECONDS}s"
ask SSH_STEP_COUNT "How many discrete manual steps did stages 3 and 4 take?"
write_env SSH_STEP_COUNT "$SSH_STEP_COUNT"
note_manifest "SSH setup total: ${SSH_SETUP_SECONDS}s across ${SSH_STEP_COUNT} manual steps"
note_manifest "  ^ measured input to the manual-Daemon-install decision in ticket 12"
pause "Continue?"

# ── Stage 5 ────────────────────────────────────────────────────────────────
stage "Host specs and VRAM"
say "The Answer on issue #4 must record these. Reading them over SSH."
printf '\n'
SPECS="$LANDING/host-specs.txt"
: > "$SPECS"
if [[ "$HOST_OS" == "windows" ]]; then
  rsh 'systeminfo | findstr /C:"OS Name" /C:"OS Version" /C:"Total Physical Memory"' >> "$SPECS" 2>&1 || true
  rsh 'wmic path win32_VideoController get name,AdapterRAM' >> "$SPECS" 2>&1 || true
else
  rsh 'sw_vers; sysctl -n machdep.cpu.brand_string; sysctl -n hw.memsize' >> "$SPECS" 2>&1 || true
  rsh 'system_profiler SPDisplaysDataType | head -40' >> "$SPECS" 2>&1 || true
fi
cat "$SPECS"
printf '\n'
say "Saved -> host-specs.txt"
note "On Apple silicon, VRAM is unified memory — record the total, not a card."
pause "Continue?"

# ── Stage 6 ────────────────────────────────────────────────────────────────
stage "Vendor — probe, install, pull a model"
say "Probing what already serves on the Host."
printf '\n'
OLLAMA_CODE=$(rsh "curl -sS -m 5 -o /dev/null -w '%{http_code}' http://127.0.0.1:11434/api/tags" 2>/dev/null || echo 000)
LMS_CODE=$(rsh "curl -sS -m 5 -o /dev/null -w '%{http_code}' http://127.0.0.1:1234/api/v1/models" 2>/dev/null || echo 000)
if [[ "$OLLAMA_CODE" == "200" ]]; then
  say "Ollama is already serving on 11434."
  VENDOR_KIND=ollama; VENDOR_URL="http://127.0.0.1:11434"
elif [[ "$LMS_CODE" == "200" ]]; then
  say "LM Studio is already serving on 1234."
  VENDOR_KIND=lmstudio; VENDOR_URL="http://127.0.0.1:1234"
else
  warn "No Vendor is serving on the Host yet."
  say "Ollama is the easier one to drive over SSH — headless, CLI model pulls."
  say "LM Studio matches the existing captures, but is GUI-first."
  printf '\n'
  ask VENDOR_KIND "Which Vendor — 'ollama' or 'lmstudio'?"
  if [[ "$VENDOR_KIND" == "ollama" ]]; then
    VENDOR_URL="http://127.0.0.1:11434"
    step "Install Ollama on the Host from https://ollama.com/download"
    note "  macOS: the .dmg, or 'brew install ollama' then 'ollama serve'"
    note "  Windows: the .exe installer; it registers a background service"
  else
    VENDOR_URL="http://127.0.0.1:1234"
    step "Install LM Studio on the Host from https://lmstudio.ai"
    step "Developer tab -> Start Server (port 1234)"
    warn "LM Studio needs a desktop session. Over SSH alone it will not start."
  fi
  printf '\n'
  pause "Vendor installed and serving?"
fi
write_env VENDOR_KIND "$VENDOR_KIND"
write_env VENDOR_URL  "$VENDOR_URL"
printf '\n'
say "The model MUST be tool-calling capable — a Harness that cannot call a tool"
say "produces a capture with nothing in it."
printf '\n'
if [[ "$VENDOR_KIND" == "ollama" ]]; then
  say "Models on the Host:"
  rsh "ollama list" 2>&1 | head -20 || true
  printf '\n'
  ask VENDOR_MODEL "Model to use (e.g. qwen3:8b):"
  if confirm "Pull '$VENDOR_MODEL' on the Host now?"; then
    rsh "ollama pull $VENDOR_MODEL" || warn "Pull failed — check the name."
  fi
  rsh "curl -sS $VENDOR_URL/api/tags" > "$LANDING/vendor-models.json" 2>&1 || true
else
  rsh "curl -sS $VENDOR_URL/api/v1/models" > "$LANDING/vendor-models.json" 2>&1 || true
  say "Model ids the Host reports:"
  grep -o '"key"[^,]*' "$LANDING/vendor-models.json" 2>/dev/null | head -20 || \
    say "  (read vendor-models.json yourself)"
  printf '\n'
  ask VENDOR_MODEL "Model to use:"
fi
write_env VENDOR_MODEL "$VENDOR_MODEL"
note_manifest "Vendor: $VENDOR_KIND at $VENDOR_URL, model $VENDOR_MODEL"
pause "Continue?"

# ── Stage 7 ────────────────────────────────────────────────────────────────
stage "Vendor over a real interface"
say "The WSL2 run reached the Vendor at 172.25.112.1 — a virtual adapter on the"
say "same box. A second physical machine gives a real NIC. That is the question"
say "a single machine could never answer."
printf '\n'
if [[ "$HOST_OS" == "windows" ]]; then
  HOST_IFACE_IP=$(rsh "powershell -NoProfile -Command \"(Get-NetIPAddress -AddressFamily IPv4 -PrefixOrigin Dhcp,Manual | Select-Object -First 1).IPAddress\"" 2>/dev/null | tr -d '\r' | head -1)
else
  HOST_IFACE_IP=$(rsh "ipconfig getifaddr en0 || ipconfig getifaddr en1" 2>/dev/null | tr -d '\r' | head -1)
fi
if [[ -z "$HOST_IFACE_IP" ]]; then
  ask HOST_IFACE_IP "Could not detect it — Host LAN IP:"
fi
write_env HOST_IFACE_IP "$HOST_IFACE_IP"
say "Host LAN IP: $HOST_IFACE_IP"
printf '\n'
IFACE_URL="${VENDOR_URL/127.0.0.1/$HOST_IFACE_IP}"
if [[ "$VENDOR_KIND" == "ollama" ]]; then
  IFACE_PATH="/api/tags"
else
  IFACE_PATH="/api/v1/models"
fi
say "Asking the Host to reach its own Vendor at $IFACE_URL$IFACE_PATH"
IFACE_CODE=$(rsh "curl -sS -m 10 -o /dev/null -w '%{http_code}' $IFACE_URL$IFACE_PATH" 2>/dev/null || echo 000)
if [[ "$IFACE_CODE" == "200" ]]; then
  printf '  %s+%s Vendor answers on the real interface\n' "$GREEN" "$RESET"
else
  warn "HTTP $IFACE_CODE — the Vendor is bound to loopback only."
  note "Ollama: set OLLAMA_HOST=0.0.0.0 and restart the service."
  note "LM Studio: Developer tab -> Serve on Local Network."
  warn "Revert this afterwards. The hermes-linux run had to, and said so."
fi
note_manifest "Vendor over real interface ($IFACE_URL$IFACE_PATH): HTTP $IFACE_CODE"
pause "Continue?"

# ── Stage 8 ────────────────────────────────────────────────────────────────
stage "Harnesses on the Host"
say "Both, or a recorded reason why one will not install. A refusal to install"
say "is a real finding, not a failure — record it and move on."
printf '\n'
VERSIONS="$LANDING/harness-versions.txt"
probe_harnesses() {
  : > "$VERSIONS"
  rsh "hermes --version" >> "$VERSIONS" 2>&1 || echo "hermes: NOT INSTALLED" >> "$VERSIONS"
  rsh "pi --version"     >> "$VERSIONS" 2>&1 || echo "pi: NOT INSTALLED"     >> "$VERSIONS"
  cat "$VERSIONS"
}
probe_harnesses
printf '\n'
if grep -q "NOT INSTALLED" "$VERSIONS"; then
  warn "At least one Harness is missing. Install on the Host:"
  note "    Hermes: pip install -e '.[acp]' from the source tree"
  note "    Pi:     npm install -g @earendil-works/pi-coding-agent"
  printf '\n'
  if confirm "Install Pi over SSH now (npm, non-interactive)?"; then
    rsh "npm install -g @earendil-works/pi-coding-agent" || warn "npm install failed."
  fi
  say "Hermes needs its source tree — install it at the Host by hand."
  pause "Done what you can?"
  probe_harnesses
fi
note_manifest "Harness versions on the Host:"
while IFS= read -r l; do note_manifest "  $l"; done < "$VERSIONS"
pause "Continue?"

# ── Stage 9 ────────────────────────────────────────────────────────────────
stage "Capture — run the existing wizards on the Host"
say "Reusing capture-hermes.sh and capture-pi.sh rather than writing new ones,"
say "so the remote transcripts are comparable with the local ones."
printf '\n'
say "Copying the capture scripts to the Host..."
scp -q ${SSH_KEY_PATH:+-i "$SSH_KEY_PATH"} -P "$SSH_PORT" \
  "$REPO_ROOT/scripts/capture-hermes.sh" "$REPO_ROOT/scripts/capture-pi.sh" \
  "$REPO_ROOT/scripts/acp-capture.py" "$REPO_ROOT/scripts/pi-rpc-capture.py" \
  "$HOST_USER@$HOST_ADDR:" && say "copied 4 files"
printf '\n'
warn "Those wizards are interactive — they need a terminal, not a pipe."
say "Each one below opens a real SSH session with a TTY. Drive it at the Host"
say "prompt, then exit to come back here."
printf '\n'
if confirm "Run capture-hermes.sh on the Host now?"; then
  ssh -t ${SSH_KEY_PATH:+-i "$SSH_KEY_PATH"} -p "$SSH_PORT" \
    "$HOST_USER@$HOST_ADDR" "bash ./capture-hermes.sh" || \
    warn "Hermes capture exited non-zero — record the code, it is a finding."
fi
printf '\n'
if confirm "Run capture-pi.sh on the Host now?"; then
  ssh -t ${SSH_KEY_PATH:+-i "$SSH_KEY_PATH"} -p "$SSH_PORT" \
    "$HOST_USER@$HOST_ADDR" "bash ./capture-pi.sh" || \
    warn "Pi capture exited non-zero — record the code, it is a finding."
fi
pause "Both captures attempted?"

# ── Stage 10 ───────────────────────────────────────────────────────────────
stage "Pull the transcripts back"
say "Raw stdout and stderr are the primary evidence the Event model gets"
say "designed against. Nothing here is a summary."
printf '\n'
say "Capture directories on the Host:"
rsh "ls -d hermes-capture-* pi-capture-* 2>/dev/null" || say "  (none found)"
printf '\n'
ask REMOTE_CAPTURE_PATH "Path on the Host to pull (e.g. pi-capture-20260820-101500):"
if [[ -n "$REMOTE_CAPTURE_PATH" ]]; then
  scp -q -r ${SSH_KEY_PATH:+-i "$SSH_KEY_PATH"} -P "$SSH_PORT" \
    "$HOST_USER@$HOST_ADDR:$REMOTE_CAPTURE_PATH" "$LANDING/" && \
    say "pulled into $LANDING"
  note "Re-run this wizard to pull the other capture directory."
fi
printf '\n'
say "Files now in $LANDING:"
ls -1 "$LANDING" | sed 's/^/    /'
printf '\n'

# The limit this Host cannot lift. Recorded here so the Answer on #4 is honest
# about it, the way hermes-linux/README.md records its own caveats.
note_manifest ""
note_manifest "LIMITS OF THIS RUN"
note_manifest "  The Host is $HOST_OS, not bare-metal Linux. The Hermes stdin"
note_manifest "  deadlock (C7) and phantom denial (C9) were disproved only under"
note_manifest "  WSL2. This run does NOT lift that caveat — a native Linux kernel"
note_manifest "  and its pipe implementation remain untested."
note_manifest "  What this run DOES establish: a separate machine over SSH key"
note_manifest "  auth, and a Vendor reached over a real network interface."
note_manifest ""
note_manifest "Finished: $(date -Iseconds)"

say "Manifest written -> $MANIFEST"
note "Next: comment the Answer on issue #4 and close it."
finish
