#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Git Bash mangles arguments that look like POSIX paths when handing them to
# native Windows executables. Turn that off for the whole run.
export MSYS_NO_PATHCONV=1
export MSYS2_ARG_CONV_EXCL='*'

# Quieter, more reproducible captures.
export PI_SKIP_VERSION_CHECK=1
export PI_TELEMETRY=0

# Unlike Hermes, Pi has no ~/.pi/.env that it reads. This file is the WIZARD's
# own bookkeeping only — it exists so re-runs can offer your previous answers
# back as defaults. Pi never reads it.
ENV_FILE="$HOME/.pi-capture.env"

CAPTURE_DIR="$HOME/pi-capture-$(date +%Y%m%d-%H%M%S)"
WORKDIR="$CAPTURE_DIR/workdir"
SESSION_DIR="$CAPTURE_DIR/sessions"
mkdir -p "$WORKDIR" "$SESSION_DIR"
MANIFEST="$CAPTURE_DIR/manifest.txt"

PY=""
PI_CMD=""
EXT_FILE="$CAPTURE_DIR/vendor-provider.ts"

note_manifest() { printf '%s\n' "$1" >> "$MANIFEST"; }

capture_get() {
  local name="$1" url="$2" code
  local out="$CAPTURE_DIR/$name"
  code=$(curl -sS -o "$out" -w '%{http_code}' "$url" 2>>"$CAPTURE_DIR/curl-errors.log" || echo "000")
  if [[ "$code" == "200" ]]; then
    printf '  %s✓%s %s → %s (%s bytes)\n' "$GREEN" "$RESET" "$url" "$name" "$(wc -c < "$out" | tr -d ' ')"
  else
    warn "$url returned HTTP $code — saved anyway as $name"
  fi
  note_manifest "GET $url -> HTTP $code -> $name"
}

# run_pi_capture LABEL OUTFILE PROMPT — one-shot --mode json run, timed out.
#
# '< /dev/null' is load-bearing, not tidiness. Pi reads stdin to EOF even when
# the prompt is passed as an argument, so at a terminal it blocks forever with
# both streams redirected and nothing on screen. Measured: instant with stdin
# closed, still hung after 60s with stdin open and silent. Every one-shot pi
# call in this wizard needs it. The --mode rpc calls must NOT have it: there
# stdin is the input channel.
run_pi_capture() {
  local label="$1" outfile="$2" prompt="$3" rc
  set +e
  if command -v timeout >/dev/null 2>&1; then
    timeout 300 $PI_CMD -e "$EXT_FILE" --provider "$VENDOR_KIND" --model "$PI_MODEL" \
      --session-dir "$SESSION_DIR" --mode json "$prompt" \
      < /dev/null > "$outfile" 2> "$CAPTURE_DIR/$label-stderr.log"
  else
    $PI_CMD -e "$EXT_FILE" --provider "$VENDOR_KIND" --model "$PI_MODEL" \
      --session-dir "$SESSION_DIR" --mode json "$prompt" \
      < /dev/null > "$outfile" 2> "$CAPTURE_DIR/$label-stderr.log"
  fi
  rc=$?
  set -e
  say "exit code: $rc   ← undocumented for Pi; record it"
  note_manifest "$label exit code: $rc"
  say "captured $(wc -l < "$outfile" | tr -d ' ') JSONL lines → $(basename "$outfile")"
}

banner "Pi → Vendor: capture raw output"

# ── Stage 1 ────────────────────────────────────────────────────────────────
stage "Preflight — Node, Pi, and tools"
say "Pi is a Node program, so this needs Node rather than Python."
printf '\n'

for c in python python3 py; do
  if command -v "$c" >/dev/null 2>&1; then PY="$c"; break; fi
done
[[ -z "$PY" ]] && { warn "No python found — needed only to read JSON. Install it or add jq."; exit 1; }
command -v curl >/dev/null 2>&1 || { warn "curl not found."; exit 1; }

if ! command -v node >/dev/null 2>&1; then
  warn "Node is not installed. Pi cannot run without it."
  say "Install Node LTS from https://nodejs.org, reopen Git Bash, re-run."
  exit 1
fi
say "node: $(node --version 2>&1)"
say "npm:  $(npm --version 2>&1 || echo 'not found')"

printf '\n'
if command -v pi >/dev/null 2>&1; then
  PI_CMD="pi"
  say "pi:   $(pi --version 2>&1 | head -n1)"
else
  warn "'pi' is not on PATH."
  say "You said this machine has Hermes and a Vendor — Pi likely isn't installed yet."
  printf '\n'
  if confirm "Install it globally now (npm i -g @earendil-works/pi-coding-agent)?"; then
    npm install -g @earendil-works/pi-coding-agent
    if command -v pi >/dev/null 2>&1; then
      PI_CMD="pi"
      say "installed: $(pi --version 2>&1 | head -n1)"
    else
      warn "Installed, but 'pi' still isn't on PATH in this shell."
      say "Falling back to npx (slower, but works)."
      PI_CMD="npx -y @earendil-works/pi-coding-agent"
    fi
  else
    say "Using npx instead — no global install."
    PI_CMD="npx -y @earendil-works/pi-coding-agent"
  fi
fi

note_manifest "=== Pi capture run: $(date -Iseconds) ==="
note_manifest "OS: Windows (Git Bash) — $(uname -a 2>/dev/null || echo unknown)"
note_manifest "node: $(node --version 2>&1)"
note_manifest "pi invocation: $PI_CMD"
note_manifest "capture dir: $CAPTURE_DIR"
note_manifest ""

printf '\n'
say "Capturing into: $CAPTURE_DIR"
pause "Ready?"

# ── Stage 2 ────────────────────────────────────────────────────────────────
stage "Vendor — find one serving, pick a model"
say "Either Vendor works. Pi reaches both the same way, through an"
say "OpenAI-compatible endpoint registered from an extension."
note "Using 127.0.0.1 rather than localhost: on Windows, localhost can resolve to"
note "::1 first and miss a server bound only to IPv4."
printf '\n'

# Probe both rather than asking first. On a Host reached over SSH the operator
# cannot see which one is running, and a wrong guess costs a whole stage.
probe_vendor() {
  curl -sS -m 5 -o /dev/null -w '%{http_code}' "$1" 2>/dev/null || echo 000
}
LMS_CODE=$(probe_vendor "http://127.0.0.1:1234/api/v1/models")
OLL_CODE=$(probe_vendor "http://127.0.0.1:11434/v1/models")
say "LM Studio on 1234:  HTTP $LMS_CODE"
say "Ollama on 11434:    HTTP $OLL_CODE"
printf '\n'

VENDOR_KIND=""
if [[ "$LMS_CODE" == 200 && "$OLL_CODE" == 200 ]]; then
  step "Both are serving. Which one is this capture against?"
  ask VENDOR_KIND "Vendor [lmstudio|ollama]:"
elif [[ "$LMS_CODE" == 200 ]]; then
  VENDOR_KIND=lmstudio
elif [[ "$OLL_CODE" == 200 ]]; then
  VENDOR_KIND=ollama
else
  warn "Neither Vendor answered."
  note "LM Studio: Developer tab -> Start Server."
  note "Ollama:    it serves on 11434 once installed; 'ollama list' to confirm."
  ask VENDOR_KIND "Carry on anyway with [lmstudio|ollama]:"
fi
[[ -z "$VENDOR_KIND" ]] && VENDOR_KIND=lmstudio

# Switching Vendor must not inherit the other one's answers. `ask` offers the
# stored value as its default and Enter keeps it, so a URL and model saved
# against LM Studio come back as the defaults for Ollama — and the capture
# quietly runs against the Vendor you did not choose. Drop them on a switch.
forget_env() {
  [[ -f "$ENV_FILE" ]] || return 0
  local tmp; tmp=$(mktemp)
  grep -vE "^${1}=" "$ENV_FILE" > "$tmp" || true
  mv "$tmp" "$ENV_FILE"
}
PREV_KIND=$(_existing VENDOR_KIND || true)
if [[ -n "$PREV_KIND" && "$PREV_KIND" != "$VENDOR_KIND" ]]; then
  forget_env VENDOR_URL; forget_env PI_MODEL; forget_env CTX
  note "Vendor changed from $PREV_KIND — cleared the saved URL, model and context."
fi
write_env VENDOR_KIND "$VENDOR_KIND"

if [[ "$VENDOR_KIND" == "ollama" ]]; then
  VENDOR_NAME="Ollama (local)"
  DEFAULT_URL="http://127.0.0.1:11434"
else
  VENDOR_NAME="LM Studio (local)"
  DEFAULT_URL="http://127.0.0.1:1234"
fi
printf '\n'
ask VENDOR_URL "$VENDOR_NAME base URL [$DEFAULT_URL]:"
[[ -z "$VENDOR_URL" ]] && VENDOR_URL="$DEFAULT_URL"
write_env VENDOR_URL "$VENDOR_URL"
printf '\n'

MODELS_JSON="$CAPTURE_DIR/vendor-models.json"
if [[ "$VENDOR_KIND" == "ollama" ]]; then
  capture_get "vendor-models.json" "$VENDOR_URL/v1/models"
  # The native endpoint carries the parameter size and quantisation that the
  # OpenAI-compatible one drops. Kept because it is evidence, not decoration.
  capture_get "ollama-tags.json" "$VENDOR_URL/api/tags"
else
  capture_get "vendor-models.json" "$VENDOR_URL/api/v1/models"
  if [[ ! -s "$MODELS_JSON" ]]; then
    say "Trying the pre-0.4.0 path..."
    capture_get "vendor-models.json" "$VENDOR_URL/api/v0/models"
  fi
fi

printf '\n'
say "Model ids found:"
$PY - "$MODELS_JSON" <<'PYEOF' 2>/dev/null || say "  (couldn't parse — read the file yourself)"
import json, sys
d = json.load(open(sys.argv[1], encoding="utf-8"))
for m in (d.get("models") or d.get("data") or []):
    ctx = m.get("max_context_length") or m.get("context_length") or "?"
    caps = m.get("capabilities")
    # Ollama's OpenAI-compatible listing carries no capability field at all.
    # Absent is not the same as false, and printing "NO TOOLS" for a model that
    # does support them would be a fabricated finding.
    if caps is None:
        tools = "tools: unknown"
    else:
        tools = "tools" if caps.get("trained_for_tool_use") else "NO TOOLS"
    # LM Studio >=0.4.0 keys this "key"; older builds use "id".
    print("   ", m.get("key") or m.get("id") or m.get("modelKey") or m.get("path"),
          " ctx:", ctx, " ", tools)
PYEOF

printf '\n'
step "Pick a TOOL-CAPABLE model — stage 6 needs it to make a tool call."
[[ "$VENDOR_KIND" == "ollama" ]] && note "Ollama does not report tool support here. 'ollama show <model>' does."
ask PI_MODEL "Model id:"
write_env PI_MODEL "$PI_MODEL"

CTX=$($PY - "$MODELS_JSON" "$PI_MODEL" <<'PYEOF' 2>/dev/null || echo ""
import json, sys
d = json.load(open(sys.argv[1], encoding="utf-8"))
for m in (d.get("models") or d.get("data") or []):
    if (m.get("key") or m.get("id") or m.get("modelKey")) == sys.argv[2]:
        print(m.get("max_context_length") or m.get("context_length") or "")
        break
PYEOF
)
if [[ -z "$CTX" ]]; then
  ask CTX "Context window (couldn't detect) [32768]:"
  [[ -z "$CTX" ]] && CTX="32768"
fi
say "context window: $CTX"
note_manifest "Vendor: $VENDOR_KIND at $VENDOR_URL"
note_manifest "Model: $PI_MODEL (ctx $CTX)"

# ── Stage 3 ────────────────────────────────────────────────────────────────
stage "Generate the provider extension"
say "This is the part with no shortcut. Pi's built-in provider list does NOT"
say "include a local Vendor, and there is no --base-url flag. An arbitrary"
say "OpenAI-compatible endpoint is only reachable by registering a provider"
say "from an extension, loaded with -e."
printf '\n'

cat > "$EXT_FILE" <<EXTEOF
export default function (pi) {
  pi.registerProvider("$VENDOR_KIND", {
    name: "$VENDOR_NAME",
    baseUrl: "$VENDOR_URL/v1",
    apiKey: "$VENDOR_KIND",
    api: "openai-completions",
    models: [
      {
        id: "$PI_MODEL",
        name: "$PI_MODEL",
        reasoning: false,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: $CTX,
        maxTokens: 4096
      }
    ]
  });
}
EXTEOF

say "Written to $(basename "$EXT_FILE"):"
sed 's/^/    /' "$EXT_FILE"
printf '\n'
note "Docs show a .ts extension with a type-only import. This file omits the"
note "import so it is valid as both TS and plain JS. If loading fails, try"
note "renaming it to .js and re-running."
printf '\n'
say "Verifying Pi can see the provider..."
set +e
$PI_CMD -e "$EXT_FILE" --list-models < /dev/null > "$CAPTURE_DIR/pi-list-models.txt" 2>&1
LIST_RC=$?
set -e
# Do NOT grep for the provider name alone: Pi prints it inside its own error
# text ('Provider "<name>": ... is required'), so a substring match reports
# success on the exact failure it is meant to catch. Require a real table row
# — provider and model on one line — and treat Pi's warnings as fatal.
# --list-models also exits 0 with no models at all, so LIST_RC proves nothing.
# Field comparison, not a regex: model ids contain '/' and '.', which turn a
# hand-escaped pattern into a debugging exercise of its own.
if [[ $LIST_RC -eq 0 ]] \
   && awk -v m="$PI_MODEL" -v p="$VENDOR_KIND" '$1==p && $2==m {found=1} END{exit !found}' \
        "$CAPTURE_DIR/pi-list-models.txt" \
   && ! grep -qi "no models available\|errors loading models.json" "$CAPTURE_DIR/pi-list-models.txt"; then
  say "  provider registered."
else
  warn "Provider did NOT register (exit $LIST_RC). Output:"
  head -n 15 "$CAPTURE_DIR/pi-list-models.txt" | sed 's/^/    /'
  printf '\n'
  note "Most common cause: ~/.pi/agent/models.json exists and is invalid. Its"
  note "errors also break -e extension loading when both define the same"
  note "provider name. The key is 'baseUrl' — camelCase. 'baseURL' is rejected."
  note "Fix or remove that file before continuing; stage 4 will otherwise hang"
  note "with both output streams redirected and nothing to show you."
  printf '\n'
  confirm "Continue anyway?" || exit 1
fi
note_manifest "extension: $(basename "$EXT_FILE"); --list-models exit $LIST_RC"
pause "Continue?"

# ── Stage 4 ────────────────────────────────────────────────────────────────
stage "Baseline — plain text via -p"
say "Cheapest possible check that the wiring works, before structured modes."
printf '\n'

cd "$WORKDIR"
set +e
# '< /dev/null' and the timeout are both required — see run_pi_capture. Without
# the redirect this call blocks on the terminal forever; without the timeout a
# genuine model stall looks identical to that hang.
if command -v timeout >/dev/null 2>&1; then
  timeout 120 $PI_CMD -e "$EXT_FILE" --provider "$VENDOR_KIND" --model "$PI_MODEL" \
    --session-dir "$SESSION_DIR" \
    -p "Reply with exactly the word: hello." \
    < /dev/null > "$CAPTURE_DIR/baseline-stdout.txt" 2> "$CAPTURE_DIR/baseline-stderr.txt"
else
  $PI_CMD -e "$EXT_FILE" --provider "$VENDOR_KIND" --model "$PI_MODEL" \
    --session-dir "$SESSION_DIR" \
    -p "Reply with exactly the word: hello." \
    < /dev/null > "$CAPTURE_DIR/baseline-stdout.txt" 2> "$CAPTURE_DIR/baseline-stderr.txt"
fi
BASE_RC=$?
set -e
if [[ $BASE_RC -eq 124 ]]; then
  warn "Timed out after 120s. The Vendor is probably loading the model, or is busy."
  warn "Check its Developer tab, then re-run this wizard."
fi
say "exit code: $BASE_RC   ← undocumented; record it"
note_manifest "pi -p exit code: $BASE_RC"
printf '\n'
say "stdout:"
sed 's/^/    /' "$CAPTURE_DIR/baseline-stdout.txt" | head -n 10
if [[ $BASE_RC -ne 0 ]]; then
  printf '\n'
  warn "Non-zero. stderr:"
  head -n 15 "$CAPTURE_DIR/baseline-stderr.txt" | sed 's/^/    /'
  confirm "Continue anyway?" || exit 1
fi
printf '\n'
pause "Ready for the structured captures?"

# ── Stage 5 ────────────────────────────────────────────────────────────────
stage "Capture the PLAIN exchange (--mode json)"
say "One-way JSONL on stdout. This is the primary artefact."
printf '\n'

cd "$WORKDIR"
run_pi_capture "plain" "$CAPTURE_DIR/plain-events.jsonl" \
  "Reply with exactly the word: hello. Do not use any tools."

printf '\n'
say "Event types seen:"
grep -oE '"type"[[:space:]]*:[[:space:]]*"[^"]+"' "$CAPTURE_DIR/plain-events.jsonl" 2>/dev/null \
  | sort | uniq -c | sed 's/^/    /' || say "    (none matched — inspect by hand)"
printf '\n'
note "Watch for a leading {\"type\":\"session\",\"version\":N,...} header line, and"
note "for whether agent_settled appears — the docs list it for RPC mode only."
printf '\n'
pause "Continue?"

# ── Stage 6 ────────────────────────────────────────────────────────────────
stage "Capture the TOOL-CALL exchange (--mode json)"
warn "Pi has NO tool approval prompt. Its docs say so explicitly: built-in tools"
warn "read, write, edit and run shell commands with the process's permissions."
warn "That is why everything here runs inside an isolated workdir."
printf '\n'
say "workdir: $WORKDIR"
printf 'alpha\nbeta\ngamma\n' > "$WORKDIR/sample.txt"
say "created sample.txt for it to find"
printf '\n'
pause "Understood — run it?"

printf '\n'
cd "$WORKDIR"
run_pi_capture "tool" "$CAPTURE_DIR/tool-events.jsonl" \
  "Use your bash tool to list the files in the current directory, then tell me how many there are."

printf '\n'
say "Event types seen:"
grep -oE '"type"[[:space:]]*:[[:space:]]*"[^"]+"' "$CAPTURE_DIR/tool-events.jsonl" 2>/dev/null \
  | sort | uniq -c | sed 's/^/    /' || say "    (none matched — inspect by hand)"
printf '\n'
note "The ordering to verify: tool_execution_start fires BEFORE the tool runs,"
note "and message_update deltas deliberately omit the cumulative snapshot —"
note "message_end carries the authoritative message."
printf '\n'
pause "Continue to the RPC probe?"

# ── Stage 7 ────────────────────────────────────────────────────────────────
stage "RPC probe (--mode rpc)"
say "This is the mode the Daemon will actually build against: long-lived,"
say "bidirectional LF-delimited JSONL over stdin/stdout."
printf '\n'
say "It settles two open questions:"
step "does -e (extension loading) work in RPC mode at all?"
step "does agent_settled appear here but not in --mode json?"
printf '\n'

# The field is 'message'. It is NOT 'prompt': that yields
# {"success":false,"error":"Cannot read properties of undefined (reading
# 'startsWith')"} — an undefined-property crash rather than a schema error, so
# the response does not tell you what the right shape was. Confirmed against
# the installed docs/rpc.md, which the local install ships in full.
cat > "$CAPTURE_DIR/rpc-command.jsonl" <<'RPCEOF'
{"id":"req-1","type":"prompt","message":"Reply with exactly the word: hello."}
RPCEOF

say "Command to send on stdin:"
sed 's/^/    /' "$CAPTURE_DIR/rpc-command.jsonl"
printf '\n'
note "'id' is optional but echoed back on the response, which is how a"
note "supervisor correlates a reply to the command that caused it."
pause "Send it?"

printf '\n'
cd "$WORKDIR"
set +e
# 'cat cmd | pi' is NOT enough: EOF on stdin makes Pi exit mid-turn. Measured
# 5 events that way (stopping at message_start) versus 54 through
# agent_settled with stdin held open. RPC is a session, not a pipe — the same
# lesson the Hermes ACP capture learned. Hold stdin open, then let the trailing
# sleep close it once the turn has settled.
#
# The sleep is a capture-harness shortcut. A real supervisor watches stdout for
# agent_settled and closes stdin on that, rather than guessing a duration.
RPC_HOLD=90
if command -v timeout >/dev/null 2>&1; then
  timeout $((RPC_HOLD + 60)) bash -c "{ cat '$CAPTURE_DIR/rpc-command.jsonl'; sleep $RPC_HOLD; } | $PI_CMD -e '$EXT_FILE' --provider '$VENDOR_KIND' --model '$PI_MODEL' --session-dir '$SESSION_DIR' --mode rpc" \
    > "$CAPTURE_DIR/rpc-events.jsonl" 2> "$CAPTURE_DIR/rpc-stderr.log"
else
  { cat "$CAPTURE_DIR/rpc-command.jsonl"; sleep $RPC_HOLD; } \
    | $PI_CMD -e "$EXT_FILE" --provider "$VENDOR_KIND" --model "$PI_MODEL" \
      --session-dir "$SESSION_DIR" --mode rpc \
    > "$CAPTURE_DIR/rpc-events.jsonl" 2> "$CAPTURE_DIR/rpc-stderr.log"
fi
RPC_RC=$?
set -e
say "exit code: $RPC_RC"
note_manifest "rpc exit code: $RPC_RC"
say "captured $(wc -l < "$CAPTURE_DIR/rpc-events.jsonl" | tr -d ' ') lines → rpc-events.jsonl"
printf '\n'
say "Event types seen:"
grep -oE '"type"[[:space:]]*:[[:space:]]*"[^"]+"' "$CAPTURE_DIR/rpc-events.jsonl" 2>/dev/null \
  | sort | uniq -c | sed 's/^/    /' || say "    (none — check rpc-stderr.log)"
printf '\n'
if grep -q "agent_settled" "$CAPTURE_DIR/rpc-events.jsonl" 2>/dev/null; then
  say "agent_settled: PRESENT in rpc"
  note_manifest "agent_settled in rpc: yes"
else
  say "agent_settled: absent in rpc"
  note_manifest "agent_settled in rpc: no"
fi
if grep -q "agent_settled" "$CAPTURE_DIR/plain-events.jsonl" 2>/dev/null; then
  say "agent_settled: PRESENT in --mode json too"
  note_manifest "agent_settled in json: yes"
else
  say "agent_settled: absent in --mode json"
  note_manifest "agent_settled in json: no"
fi
printf '\n'
pause "Wrap up?"

# ── Stage 8 ────────────────────────────────────────────────────────────────
stage "Session files, stray files, and bundle"

say "Pi writes a JSONL session tree. We pointed --session-dir at the capture,"
say "so the on-disk format is already collected:"
printf '\n'
find "$SESSION_DIR" -name '*.jsonl' 2>/dev/null | sed 's/^/    /' | head -n 10 || say "    (none found)"
SESS_COUNT=$(find "$SESSION_DIR" -name '*.jsonl' 2>/dev/null | wc -l | tr -d ' ')
say "  $SESS_COUNT session file(s)"
note_manifest "session files captured: $SESS_COUNT"

printf '\n'
say "Files Pi left in the workdir (beyond the sample.txt we made):"
find "$WORKDIR" -type f ! -name 'sample.txt' 2>/dev/null | sed 's/^/    /' | head -n 20 || true
printf '\n'

note_manifest ""
note_manifest "Finished: $(date -Iseconds)"

say "Everything is in:"
say "  $CAPTURE_DIR"
printf '\n'
ls -1 "$CAPTURE_DIR" | sed 's/^/    /'
printf '\n'
say "The files that matter most:"
say "  plain-events.jsonl     ← the plain exchange"
say "  tool-events.jsonl      ← the tool-call payloads"
say "  rpc-events.jsonl       ← the surface the Daemon will actually use"
say "  sessions/*.jsonl       ← Pi's on-disk session format"
printf '\n'
step "Copy the folder into the repo as docs/research/captures/pi/"
step "Then pair it with the Hermes capture to design the Event model."
printf '\n'
note "Nothing secret was captured here — a local Vendor needs no real API key."

finish
