#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# ──────────────────────────────────────────────────────────────────────────
# Hermes is driven here over ACP (Agent Client Protocol) — `hermes acp` —
# NOT over `hermes serve`.
#
# An earlier version of this wizard targeted `POST /v1/runs` and
# `GET /v1/runs/{id}/events`. Those endpoints do not exist. Hermes v0.19.0's
# HTTP API is mounted entirely under /api/*, /openapi.json enumerates it, and
# the only WebSocket event channel (/api/events) is dashboard plumbing: it is
# gated behind _DASHBOARD_EMBEDDED_CHAT_ENABLED, its subscribers are
# receive-only, and it is fed by the PTY sidecar. There is no run-control
# REST surface at all.
#
# `hermes acp` is the real structured surface, and it is an open standard
# (JSON-RPC 2.0 over newline-delimited JSON on stdio) rather than something
# to reverse-engineer. That makes Hermes and Pi the same integration SHAPE —
# subprocess with structured stdio — which is a finding in its own right.
# ──────────────────────────────────────────────────────────────────────────

# This file is the WIZARD's own bookkeeping, so re-runs can offer your previous
# answers back as defaults. Hermes never reads it.
#
# Hermes' real config lives at %LOCALAPPDATA%\hermes\config.yaml (+ .env), which
# `GET /api/status` reports as hermes_home. This wizard READS that config and
# records it. It deliberately never writes it: the previous version wrote
# OPENAI_BASE_URL into ~/.hermes/.env, which Hermes does not read, and the
# resulting captures were silently meaningless.
ENV_FILE="$HOME/.hermes-capture.env"

CAPTURE_DIR="$HOME/hermes-capture-$(date +%Y%m%d-%H%M%S)"
WORKDIR="$CAPTURE_DIR/workdir"
mkdir -p "$WORKDIR"
MANIFEST="$CAPTURE_DIR/manifest.txt"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ACP_CLIENT="$SCRIPT_DIR/acp-capture.py"

PY=""
GIT_BASH_WIN=""

note_manifest() { printf '%s\n' "$1" >> "$MANIFEST"; }

# winpath PATH — a POSIX path as Windows sees it. Native programs (python.exe,
# hermes.exe) cannot open /c/Users/... — they read it as drive-relative and
# silently land somewhere else.
winpath() {
  if command -v cygpath >/dev/null 2>&1; then cygpath -m "$1"; else printf '%s' "$1"; fi
}

# fetch URL OUTFILE — GET a URL, writing the body with the SHELL rather than
# curl's -o. curl here is a native Windows build: hand it a POSIX path and it
# fails with "Failure writing output to destination, passed N returned -1".
# Redirection sidesteps the question entirely.
fetch() {
  local url="$1" out="$2" body code
  body=$(curl -sS -w $'\n%{http_code}' --max-time 15 "$url" 2>>"$CAPTURE_DIR/curl-errors.log") || body=$'\n000'
  code=$(printf '%s' "$body" | tail -n1)
  printf '%s' "$body" | sed '$d' > "$out"
  if [[ "$code" == "200" ]]; then
    printf '  %s✓%s %s → %s (%s bytes)\n' "$GREEN" "$RESET" "$url" "$(basename "$out")" "$(wc -c < "$out" | tr -d ' ')"
  else
    warn "$url returned HTTP $code — saved anyway as $(basename "$out")"
  fi
  note_manifest "GET $url -> HTTP $code -> $(basename "$out")"
}

# capture_acp LABEL TIMEOUT PROMPT [EXTRA...] — one recorded ACP conversation.
capture_acp() {
  local label="$1" timeout="$2" prompt="$3" rc
  shift 3
  local -a extra=("$@")
  # An array, not ${VAR:+...}: the bash path contains spaces ("Program Files"),
  # and an unquoted conditional expansion would split it into two arguments.
  local -a envargs=()
  [[ -n "$GIT_BASH_WIN" ]] && envargs=(--env "HERMES_GIT_BASH_PATH=$GIT_BASH_WIN")
  set +e
  "$PY" "$(winpath "$ACP_CLIENT")" \
    --agent-cmd "hermes acp" \
    --cwd "$(winpath "$WORKDIR")" \
    --outdir "$(winpath "$CAPTURE_DIR")" \
    --label "$label" \
    --timeout "$timeout" \
    "${envargs[@]}" \
    "${extra[@]}" \
    --prompt "$prompt"
  rc=$?
  set -e
  note_manifest "acp capture '$label' -> exit $rc"
  return $rc
}

banner "Hermes → ACP: capture raw protocol frames"

# ── Stage 1 ────────────────────────────────────────────────────────────────
stage "Preflight — hermes, ACP mode, and the capture client"
say "Checking everything this needs before touching anything."
printf '\n'

for c in python python3 py; do
  if command -v "$c" >/dev/null 2>&1; then PY="$c"; break; fi
done
if [[ -z "$PY" ]]; then
  warn "No python on PATH. Hermes is a Python program, so this is surprising."
  exit 1
fi
say "python:  $PY ($($PY --version 2>&1))"

command -v curl >/dev/null 2>&1 || { warn "curl not found — unexpected in Git Bash."; exit 1; }

if ! command -v hermes >/dev/null 2>&1; then
  warn "hermes is not on PATH in this shell."
  say "Open the shell where 'hermes --version' works, then re-run."
  exit 1
fi
say "hermes:  $(hermes --version 2>&1 | head -n1)"

if [[ ! -f "$ACP_CLIENT" ]]; then
  warn "Can't find the ACP capture client next to this script:"
  say "  $ACP_CLIENT"
  say "It lives at scripts/acp-capture.py in the repo. Run this wizard from there."
  exit 1
fi
say "client:  $ACP_CLIENT"

printf '\n'
say "Verifying ACP mode is installed (adapter imports + dependencies)..."
set +e
hermes acp --check > "$CAPTURE_DIR/acp-check.txt" 2>&1
ACP_CHECK_RC=$?
set -e
if [[ $ACP_CHECK_RC -eq 0 ]]; then
  say "  'hermes acp --check' passed."
else
  warn "'hermes acp --check' exited $ACP_CHECK_RC. Output:"
  head -n 12 "$CAPTURE_DIR/acp-check.txt" | sed 's/^/    /'
  confirm "Continue anyway?" || exit 1
fi
note_manifest "hermes acp --check exit: $ACP_CHECK_RC"

# Hermes shells out through Git Bash for its terminal tool. On this machine it
# inherits HERMES_GIT_BASH_PATH=...\Git\bin\bash.exe, fails to start it from
# inside an MSYS shell, and burns minutes before falling back to
# ...\Git\usr\bin\bash.EXE. Hand it the working path up front.
for b in "/c/Program Files/Git/usr/bin/bash.exe" "/usr/bin/bash.exe"; do
  if [[ -x "$b" ]]; then GIT_BASH_WIN="$(winpath "$b")"; break; fi
done
if [[ -n "$GIT_BASH_WIN" ]]; then
  say "git bash for Hermes' terminal tool: $GIT_BASH_WIN"
else
  warn "Couldn't find Git's usr/bin/bash.exe — the first tool call may be slow."
fi

note_manifest "=== Hermes ACP capture run: $(date -Iseconds) ==="
note_manifest "OS: Windows (Git Bash) — $(uname -a 2>/dev/null || echo unknown)"
note_manifest "python: $($PY --version 2>&1)"
note_manifest "hermes: $(hermes --version 2>&1 | head -n1)"
note_manifest "hermes acp --version: $(hermes acp --version 2>&1 | head -n1)"
note_manifest "capture dir: $CAPTURE_DIR"
note_manifest ""

printf '\n'
say "Capturing into: $CAPTURE_DIR"
pause "Looks right?"

# ── Stage 2 ────────────────────────────────────────────────────────────────
stage "Record the wiring — Hermes' own config, and the Vendor"
say "Reading Hermes' real configuration. Nothing here is written."
printf '\n'

HERMES_HOME="${LOCALAPPDATA:-$HOME/AppData/Local}/hermes"
HERMES_CONFIG="$HERMES_HOME/config.yaml"
if [[ -f "$HERMES_CONFIG" ]]; then
  say "config: $HERMES_CONFIG"
  printf '\n'
  sed -n '1,12p' "$HERMES_CONFIG" | sed 's/^/    /'
  # The model block is the wiring that matters; keep a verbatim copy.
  sed -n '1,12p' "$HERMES_CONFIG" > "$CAPTURE_DIR/hermes-config-model-block.yaml"
  LM_BASE=$(grep -E '^\s*base_url:' "$HERMES_CONFIG" | head -n1 | sed 's/.*base_url:[[:space:]]*//')
  note_manifest "hermes config: $HERMES_CONFIG"
  note_manifest "hermes base_url: $LM_BASE"
else
  warn "No config.yaml at $HERMES_CONFIG"
  ask LM_BASE "Vendor base URL [http://127.0.0.1:1234/v1]:"
  [[ -z "$LM_BASE" ]] && LM_BASE="http://127.0.0.1:1234/v1"
fi

printf '\n'
note "Note the key is 'base_url' in config.yaml — not OPENAI_BASE_URL. That"
note "naming question was item 7 on the harness research list; this settles it."

printf '\n'
LM_ROOT="${LM_BASE%/v1}"
say "Checking the Vendor is actually serving at $LM_ROOT ..."
fetch "$LM_ROOT/api/v1/models" "$CAPTURE_DIR/lmstudio-models.json"
if [[ ! -s "$CAPTURE_DIR/lmstudio-models.json" ]]; then
  say "Trying the pre-0.4.0 path..."
  fetch "$LM_ROOT/api/v0/models" "$CAPTURE_DIR/lmstudio-models-v0.json"
fi

printf '\n'
say "Models the Vendor is offering:"
$PY - "$(winpath "$CAPTURE_DIR/lmstudio-models.json")" <<'PYEOF' 2>/dev/null || say "  (couldn't parse — read the file yourself)"
import json, sys
d = json.load(open(sys.argv[1], encoding="utf-8"))
for m in (d.get("models") or d.get("data") or []):
    caps = m.get("capabilities") or {}
    tools = "tools" if caps.get("trained_for_tool_use") else "NO TOOLS"
    ident = m.get("key") or m.get("id") or m.get("modelKey") or m.get("path")
    print(f"    {ident:<45} ctx {m.get('max_context_length') or '?':<8} {tools}")
PYEOF

printf '\n'
warn "Hermes uses whichever model its own config names. If that model is not"
warn "tool-capable, stage 5 will produce no tool_call and the capture is wasted."
pause "Checked?"

# ── Stage 3 ────────────────────────────────────────────────────────────────
stage "Baseline — one-shot plain text, no protocol involved"
say "'hermes -z' prints the final response and nothing else. Cheapest possible"
say "proof the model wiring works, and it gives us the exit code (undocumented)."
printf '\n'

cd "$WORKDIR"
set +e
hermes -z "Reply with exactly the word: hello. Do not use any tools." \
  > "$CAPTURE_DIR/baseline-stdout.txt" 2> "$CAPTURE_DIR/baseline-stderr.txt"
BASELINE_EXIT=$?
set -e

say "exit code: $BASELINE_EXIT   ← record this, it is undocumented"
note_manifest "hermes -z exit code: $BASELINE_EXIT"
printf '\n'
say "stdout was:"
sed 's/^/    /' "$CAPTURE_DIR/baseline-stdout.txt" | head -n 10
printf '\n'
if [[ "$BASELINE_EXIT" -ne 0 ]]; then
  warn "Non-zero exit. Check baseline-stderr.txt before going on:"
  say "  $CAPTURE_DIR/baseline-stderr.txt"
  confirm "Continue anyway?" || exit 1
fi
pause "Ready for the first ACP capture?"

# ── Stage 4 ────────────────────────────────────────────────────────────────
stage "Capture the PLAIN exchange over ACP"
say "This is the primary artefact: every JSON-RPC frame in both directions,"
say "recorded as sent and received."
printf '\n'
note "The capture client is a real ACP client, not a pipe. ACP is bidirectional —"
note "the agent calls back for permission decisions and file reads, so a plain"
note "'cat cmds.jsonl | hermes acp' would hang. It answers those and logs them."
printf '\n'
say "Expect roughly a minute. No tools should be involved."
pause "Run it?"
printf '\n'

capture_acp "plain" 600 "Reply with exactly the word: hello. Do not use any tools." || true

printf '\n'
say "Written: plain-raw.log, plain-frames.jsonl, plain-summary.json"
note "Watch for session/update kinds that are NOT in the ACP 0.9.0 schema —"
note "'usage_update' is one. Vendor extensions to a standard protocol are"
note "exactly what the Event model has to survive."
printf '\n'
pause "Press Enter for the tool-call capture."

# ── Stage 5 ────────────────────────────────────────────────────────────────
stage "Capture the TOOL-CALL exchange over ACP"
say "Same again, but with a prompt that forces a tool. This yields the"
say "tool_call / tool_call_update payloads the Event model is blocked on."
printf '\n'

printf 'alpha\nbeta\ngamma\n' > "$WORKDIR/sample.txt"
say "Created $WORKDIR/sample.txt for it to find."
printf '\n'

warn "KNOWN DEFECT — Hermes v0.19.0 deadlocks its terminal tool in ACP mode on"
warn "Windows until the client closes stdin. The spawned sandbox shell appears to"
warn "inherit the ACP stdin pipe and block reading it."
printf '\n'
say "Measured: the tool's duration tracked the client's timeout exactly —"
say "  272.7s of 280   418.8s of 420   898.6s of 900   118.8s of 120"
say "and with stdin closed up front the same setup took 1.18s. It is a deadlock,"
say "not a slow sandbox."
printf '\n'
say "So this stage runs with --close-stdin-on-tool-call: stdin is held open until"
say "the first tool_call notification arrives, then closed to release the tool."
printf '\n'
warn "The trade: Hermes stops emitting once stdin closes, so this capture ends at"
warn "tool_call. tool_call_update and the session/prompt response are NOT captured."
warn "Record that as a gap — it is a Hermes defect, not a capture failure."
printf '\n'
note "Approvals: whether a session/request_permission arrives at all depends on"
note "Hermes' approval config. The client auto-allows and logs the full payload."
note "Absence of one is a finding, not a failure."
printf '\n'
say "Expect roughly 20 seconds."
pause "Start it?"
printf '\n'

capture_acp "tool" 300 "Use your terminal tool to list the files in the current directory, then tell me how many there are." --close-stdin-on-tool-call || true

printf '\n'
say "Written: tool-raw.log, tool-frames.jsonl, tool-summary.json"
printf '\n'
pause "Press Enter to wrap up."

# ── Stage 6 ────────────────────────────────────────────────────────────────
stage "Stray files and bundle"

say "Checking whether Hermes littered its working directory..."
printf '\n'
FOUND_STRAY=""
for f in trajectory_samples.jsonl failed_trajectories.jsonl; do
  if [[ -f "$WORKDIR/$f" ]]; then
    say "  found $f ($(wc -c < "$WORKDIR/$f" | tr -d ' ') bytes) — copying"
    cp "$WORKDIR/$f" "$CAPTURE_DIR/"
    FOUND_STRAY="yes"
    note_manifest "stray file confirmed: $f"
  fi
done
if [[ -z "$FOUND_STRAY" ]]; then
  say "  none — trajectory files did not appear in cwd."
  note_manifest "stray trajectory files: none observed"
fi

printf '\n'
say "Everything else Hermes left in the workdir:"
find "$WORKDIR" -type f ! -name 'sample.txt' 2>/dev/null | sed 's/^/    /' | head -n 20 || true

printf '\n'
say "Event kinds across both captures:"
for s in "$CAPTURE_DIR/plain-summary.json" "$CAPTURE_DIR/tool-summary.json"; do
  [[ -f "$s" ]] || continue
  printf '\n'
  say "  $(basename "$s"):"
  $PY - "$(winpath "$s")" <<'PYEOF' 2>/dev/null || say "    (couldn't parse)"
import json, sys
d = json.load(open(sys.argv[1], encoding="utf-8"))
print("     stopReason:", d.get("stop_reason"), " agent exit:", d.get("agent_exit_code"))
for k, n in sorted((d.get("session_update_kinds") or {}).items(), key=lambda kv: -kv[1]):
    print(f"     {n:5}  {k}")
if d.get("permission_request_count"):
    print("     permission requests:", d["permission_request_count"])
PYEOF
  note_manifest "$(basename "$s"): captured"
done

note_manifest ""
note_manifest "Finished: $(date -Iseconds)"

printf '\n'
say "Everything is in:"
say "  $CAPTURE_DIR"
printf '\n'
ls -1 "$CAPTURE_DIR" | sed 's/^/    /'

printf '\n'
say "The files that matter most:"
say "  plain-raw.log / plain-frames.jsonl   ← the plain exchange"
say "  tool-raw.log  / tool-frames.jsonl    ← the tool-call payloads"
say "  *-summary.json                       ← stopReason, usage, event tallies"
printf '\n'
step "Copy the whole folder into the repo as docs/research/captures/hermes/"
step "Then resolve ticket 03 with the manifest contents."
printf '\n'
note "Nothing secret is captured here — ACP mode needs no API key, and the"
note "Vendor is local."

finish
